### ISSUE TITLE
preview don't remove from window

### ISSUE THREAD

**Issue by CivelXu** [naturaln0va/VisualActivityViewController#1]
preview don't remove from window, will create constraint bug, I think  you should remove it by this code;

```
 override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        UIView.animate(withDuration: fadeOutDuration) {
            self.preview?.alpha = 0
            if let window = self.view.window,
                window.subviews.contains(self.preview) {
                self.preview.removeFromSuperview()
            }
        }
    }
```

**Comment by naturaln0va** [comment]
Thanks for pointing this out. I fixed this by adding the preview to the `UIActivityViewController`'s view's superview. You can see this fix in this commit: https://github.com/naturaln0va/VisualActivityViewController/commit/7de8d3bd8426c990e045243c891773a26a980550.
