### ISSUE TITLE
applicationActivities

### ISSUE THREAD

**Issue by ghost** [naturaln0va/VisualActivityViewController#2]
Please add applicationActivities to VisualActivityViewController
example : VisualActivityViewController(text: "", applicationActivities: Freedom.browsers())

**Comment by naturaln0va** [comment]
You are now able to pass your custom application activities using the `activities` param on the continence initializers: 0aed5372ab0ccf8d5f536b70f59a2184e16c4712. Previous to this commit you were also able to use the default initializer from **UIActivityViewController** to pass in your custom activities.

I hope this helps!
